{% set version="1.3.0.20181213193421" %}

package:
  name: arvados-python-client
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/53/b8/0a6c453e278858c8331f3ed75987287db6b9b55ac40f7d1e07d972ecbd8e/arvados-python-client-{{ version }}.tar.gz
  sha256: e10fd4b14f114650afad3cb31728010e0fa7f1922056310660c3f0077e124e66

build:
  number: 0
  skip: True # [not py27]

requirements:
  host:
    - python
    - setuptools
    - ciso8601 <=1.0.4,>=1.0.0
    - future
    - google-api-python-client <1.7,>=1.6.2
    - httplib2
    - oauth2client <2,>=1.4.6
    - pycurl <7.21.5,>=7.19.5.1
    - python-gflags
    - requests
    - rsa
    - urllib3 >1.12
    - ws4py <0.4,>=0.3.5

  run:
    - python
    - ciso8601 <=1.0.4,>=1.0.0
    - future
    - google-api-python-client <1.7,>=1.6.2
    - httplib2
    - oauth2client <2,>=1.4.6
    - pycurl <7.21.5,>=7.19.5.1
    - python-gflags
    - requests
    - rsa
    - urllib3 >1.12
    - ws4py <0.4,>=0.3.5

test:
  imports:
    - arvados

about:
  home: https://github.com/curoverse/arvados/tree/master/sdk/python
  license: Apache License 2.0
  summary: Python API for Arvados, an open source platform for managing and analyzing biomedical big data

extra:
  skip-lints:
    - uses_setuptools
