{% set version = "1.1" %}
{% set sha256 = "f580f28f1bf6270fdf381cc7571a56eb83269daa0e1808b86a0477ef9dd8f8b8" %}

package:
  name: libdeflate
  version: {{ version }}

source:
  url: https://github.com/ebiggers/libdeflate/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('libdeflate', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
  run:

test:
  commands:
    - echo "hey"

about:
  home: https://github.com/ebiggers/libdeflate
  license: MIT
  summary: libdeflate is a library for fast, whole-buffer DEFLATE-based compression and decompression.
