{% set version = "1.16.1" %}
{% set name = "flowCHIC" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 06b6079b083dbfc830b3d2af96eb9907664100cacb12c42f49f3a7d76460e290
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-ebimage >=4.24.0,<4.25.0'
    - 'bioconductor-flowcore >=1.48.0,<1.49.0'
    - r-base
    - r-ggplot2
    - r-hexbin
    - r-vegan
  run:
    - 'bioconductor-ebimage >=4.24.0,<4.25.0'
    - 'bioconductor-flowcore >=1.48.0,<1.49.0'
    - r-base
    - r-ggplot2
    - r-hexbin
    - r-vegan
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'A package to analyze flow cytometric data of complex microbial communities based on histogram images'

