{% set version = "1.4.1" %}
{% set name = "MIRA" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e969447ee721515af2a308b6651b3f3dac524055255f32b475133073758cc473
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, parallel, testthat, BiocStyle, rmarkdown, AnnotationHub, LOLA
requirements:
  host:
    - 'bioconductor-biobase >=2.42.0,<2.43.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.29.0'
    - 'bioconductor-bsseq >=1.18.0,<1.19.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.35.0'
    - 'bioconductor-iranges >=2.16.0,<2.17.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.21.0'
    - r-base
    - r-data.table
    - r-ggplot2
  run:
    - 'bioconductor-biobase >=2.42.0,<2.43.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.29.0'
    - 'bioconductor-bsseq >=1.18.0,<1.19.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.35.0'
    - 'bioconductor-iranges >=2.16.0,<2.17.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.21.0'
    - r-base
    - r-data.table
    - r-ggplot2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'MIRA measures the degree of "dip" in methylation level surrounding a regulatory site of interest, such as a transcription factor binding site, for instances of that type of site across the genome which can then be used to infer regulatory activity.'

