package:
  name: rvtests 
  version: "20181226"

build:
  number: 0
 
source:
  url: https://github.com/zhanxw/rvtests/archive/20181226.tar.gz
  sha256: 647d39b76a08b18c0f49eeab7e0f1d6eb737d1c1f0327b798610a06bb0ed3a30

channels:
    - defaults
    - conda-forge

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - wget # [not osx]
    - zlib
    - unzip
    - curl # [osx]
  host:
    - zlib
    - clangdev  # [osx]
    - libcxx 4.0.*  # [osx]
    - openmp 4.0.*  # [osx]
  run:
    - zlib
    - libcxx >=4.0  # [osx]
    - openmp >=4.0  # [osx]

test:
  commands:
    - rvtest --help 

about:
  home: https://github.com/zhanxw/rvtests
  license: GPL
  summary: Rare variant test software for next generation sequencing data

extra:
  identifiers:
    - doi:10.1093/bioinformatics/btw079
    - biotools:rvtests
