{% set version = "2.8.1" %}
{% set sha256_linux = "6c8216ba652d0af1c11b7e368c988fad58f2cb7ff66c2f2a05c826eac69728a6" %}
{% set sha256_osx = "ce7f517063ea21e01e8a4341dfb921b68ec73e0706fd15de19dba22a38ff57fc" %}

package:
  name: blast
  version: {{ version }}

source:
  url: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/{{ version }}/ncbi-blast-{{ version }}+-x64-linux.tar.gz # [linux]
  sha256: {{ sha256_linux }} # [linux]
  url: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/{{ version }}/ncbi-blast-{{ version }}+-x64-macosx.tar.gz # [osx]
  sha256: {{ sha256_osx }} # [osx]

build:
  number: 0

requirements:
  host:
    - boost
    - zlib
    - bzip2
    - gnutls # [linux]
    - openssl # [osx]
    - nettle 3.3|3.3.*
    - pcre
  run:
    - boost
    - zlib
    - bzip2
    - gnutls # [linux]
    - openssl # [osx]
    - nettle 3.3|3.3.*
    - pcre
    - perl
    - perl-list-moreutils
    - perl-archive-tar

test:
  files:
    - test.fa
    - testdatabase.fa
  commands:
    # (see run_tests.sh for remainder of tests)
    - blastn -help
    - blastp -help
    - makeblastdb -help
    # test that BLAST ignores LD_LIBRARY_PATH
    - touch libstdc++.so.6; LD_LIBRARY_PATH=. makeblastdb -help && rm libstdc++.so.6
    # - update_blastdb.pl --help (disabled as it now starts a pager, stalling forever)

about:
  home: http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs
  license: Public Domain
  summary: BLAST+ is a new suite of BLAST tools that utilizes the NCBI C++ Toolkit.

extra:
  identifiers:
    - biotools:blast
    - doi:10.1016/S0022-2836(05)80360-2
