{% set version = "1.4.2" %}
{% set name = "apeglm" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 2b634428c12a9ff6cdc5422e5bdfe3a10b8cbc0f59ea0327ab4ff0ce48a8d08f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: DESeq2, airway, knitr, rmarkdown, testthat
requirements:
  host:
    - 'bioconductor-genomicranges >=1.34.0,<1.35.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.13.0'
    - r-base
    - r-emdbook
    - r-rcpp
    - r-rcppeigen
    - r-rcppnumerical
  run:
    - 'bioconductor-genomicranges >=1.34.0,<1.35.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.13.0'
    - r-base
    - r-emdbook
    - r-rcpp
    - r-rcppeigen
    - r-rcppnumerical
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'apeglm provides Bayesian shrinkage estimators for effect sizes for a variety of GLM models, using approximation of the posterior for individual coefficients.'
extra:
  parent_recipe:
    name: bioconductor-apeglm
    path: recipes/bioconductor-apeglm
    version: 1.2.1

