{% set version = "1.12.1" %}
{% set name = "cellTree" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: e01bba4d887fdecbd3c70d21e69319d7f1405e387c952b97dcd3e395864326e3
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, HSMMSingleCell, biomaRt, org.Hs.eg.db, Biobase, tools
requirements:
  host:
    - 'bioconductor-topgo >=2.34.0,<2.35.0'
    - r-base
    - r-gplots
    - r-igraph
    - r-maptpx
    - r-slam
    - r-topicmodels
    - r-xtable
  run:
    - 'bioconductor-topgo >=2.34.0,<2.35.0'
    - r-base
    - r-gplots
    - r-igraph
    - r-maptpx
    - r-slam
    - r-topicmodels
    - r-xtable
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This packages computes a Latent Dirichlet Allocation (LDA) model of single-cell RNA-seq data and builds a compact tree modelling the relationship between individual cells over time or space.'

