{% set version = "1.2.1" %}
{% set name = "MetaNeighbor" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 777b513ccff8850f913563af35251467f0ffa84ba9955af9369cbb3a7e23fe00
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr (>= 1.17), rmarkdown (>= 1.6), testthat (>= 1.0.2)
requirements:
  host:
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.13.0'
    - r-base
    - 'r-beanplot >=1.2'
    - 'r-gplots >=3.0.1'
    - 'r-rcolorbrewer >=1.1'
  run:
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.13.0'
    - r-base
    - 'r-beanplot >=1.2'
    - 'r-gplots >=3.0.1'
    - 'r-rcolorbrewer >=1.1'
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'MetaNeighbor allows users to quantify cell type replicability across datasets using neighbor voting.'

