{% set version = "1.4.1" %}
{% set name = "bcSeq" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 6e2a6e545f398bf853e73379d1aec826f12b25df2ac6dc7a8f05c140c6faf547
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: knitr
requirements:
  host:
    - 'bioconductor-biostrings >=2.50.0,<2.51.0'
    - r-base
    - r-matrix
    - 'r-rcpp >=0.12.12'
  run:
    - 'bioconductor-biostrings >=2.50.0,<2.51.0'
    - r-base
    - r-matrix
    - 'r-rcpp >=0.12.12'
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'This Rcpp-based package implements a highly efficient data structure and algorithm for performing alignment of short reads from CRISPR or shRNA screens to reference barcode library. Sequencing error are considered and matching qualities are evaluated based on Phred scores. A Bayes'' classifier is employed to predict the originating barcode of a read. The package supports provision of user-defined probability models for evaluating matching qualities. The package also supports multi-threading.'

