{% set version = "1.14.1" %}
{% set name = "PROPER" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 71d5764230b0685ad3ca896e1b90070838c8e650910a20b1272fb024b7bb9bf1
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle,DESeq,DSS,knitr
requirements:
  host:
    - 'bioconductor-edger >=3.24.0,<3.25.0'
    - r-base
  run:
    - 'bioconductor-edger >=3.24.0,<3.25.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL
  summary: 'This package provide simulation based methods for evaluating the statistical power in differential expression analysis from RNA-seq data.'
extra:
  identifiers:
    - biotools:proper
  parent_recipe:
    name: bioconductor-proper
    path: recipes/bioconductor-proper
    version: 1.12.0

