{% set version = "1.4.1" %}
{% set name = "seqcombo" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: a8483beac5ef7c8d3f061e3cb7ce0592ded2648cd9192b19d7b4d09c38e78600
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: emojifont, knitr, prettydoc, tibble
requirements:
  host:
    - 'bioconductor-biostrings >=2.50.0,<2.51.0'
    - r-base
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-igraph
    - r-magrittr
    - r-rvcheck
  run:
    - 'bioconductor-biostrings >=2.50.0,<2.51.0'
    - r-base
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-igraph
    - r-magrittr
    - r-rvcheck
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Provides useful functions for visualizing sequence recombination and virus reassortment events.'

