{% set version = "1.22.1" %}
{% set name = "TCC" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 61802e0c8fa27e141530cd0db7aea6edd8d64b9d10b39336cbd3b6774ba6d279
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: RUnit, BiocGenerics
requirements:
  host:
    - 'bioconductor-bayseq >=2.16.0,<2.17.0'
    - 'bioconductor-deseq >=1.34.0,<1.35.0'
    - 'bioconductor-deseq2 >=1.22.0,<1.23.0'
    - 'bioconductor-edger >=3.24.0,<3.25.0'
    - 'bioconductor-roc >=1.58.0,<1.59.0'
    - r-base
  run:
    - 'bioconductor-bayseq >=2.16.0,<2.17.0'
    - 'bioconductor-deseq >=1.34.0,<1.35.0'
    - 'bioconductor-deseq2 >=1.22.0,<1.23.0'
    - 'bioconductor-edger >=3.24.0,<3.25.0'
    - 'bioconductor-roc >=1.58.0,<1.59.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'This package provides a series of functions for performing differential expression analysis from RNA-seq count data using robust normalization strategy (called DEGES). The basic idea of DEGES is that potential differentially expressed genes or transcripts (DEGs) among compared samples should be removed before data normalization to obtain a well-ranked gene list where true DEGs are top-ranked and non-DEGs are bottom ranked. This can be done by performing a multi-step normalization strategy (called DEGES for DEG elimination strategy). A major characteristic of TCC is to provide the robust normalization methods for several kinds of count data (two-group with or without replicates, multi-group/multi-factor, and so on) by virtue of the use of combinations of functions in depended packages.'
extra:
  identifiers:
    - biotools:tcc
  parent_recipe:
    name: bioconductor-tcc
    path: recipes/bioconductor-tcc
    version: 1.20.1

