package:
  name: pylibseq
  version: "0.2.1"

source:
  url: https://files.pythonhosted.org/packages/86/f9/0da11046680d74ceba0aade1bca859951479eacc4bda2bf062a568216cb4/pylibseq-0.2.1.tar.gz
  sha256: 6bfc509f90832f38e9c9ca862b8f57e35a68ba2b218a1092e3c18affef41f6dd

build:
  skip: True # [py27]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - libsequence >=1.9.3
    - pybind11 >=2.2.0

  run:
    - python
    - {{ pin_compatible('libsequence', max_pin='x.x') }} # max pin is guess
    - msprime

test:
  imports:
    - libsequence

about:
  home: http://pypi.python.org/pypi/pylibseq
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: 'A Python interface to libsequence'

