{% set version = '0.4.29' %}

package:
  name: ucsc-cell-browser
  version: {{ version }}

source:
  url: https://github.com/maximilianh/cellBrowser/archive/v{{ version }}.tar.gz
  sha256: ee4188757e1e88e8cc1520e58bfefddd365f71bc734ce20c3c3117ca90649636

build:
  number: 0
  noarch: python

requirements:
    host:
        - python >=3.6
    run:
        - python >=3.6
        - numpy
        - r-data.table
        - r-argparser
        - r-matrix
        - anndata

test:
    commands:
        - which cbBuild
        - which cbGuessGencode
        - which cbImportSeurat
        - which cbMarkerAnnotate
        - which cbScanpy
        - which cbImportScanpy
        - which cbImportCellranger
        - which cbTool
        - which cbUpgrade

about:
  home: http://cells.ucsc.edu
  license: GPL
  license_file: LICENSE
  summary: A browser for single-cell data, main site at http://cells.ucsc.edu
