{% set version = "1.20.1" %}
{% set name = "BEAT" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 0010e0ed0590a6831efdb8ae3a84a9de18f1f8ee86ad799be8beb990b87b2ef7
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-biostrings >=2.50.0,<2.51.0'
    - 'bioconductor-bsgenome >=1.50.0,<1.51.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.35.0'
    - 'bioconductor-shortread >=1.40.0,<1.41.0'
    - r-base
  run:
    - 'bioconductor-biostrings >=2.50.0,<2.51.0'
    - 'bioconductor-bsgenome >=1.50.0,<1.51.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.35.0'
    - 'bioconductor-shortread >=1.40.0,<1.41.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'LGPL (>= 3.0)'
  summary: 'Model-based analysis of single-cell methylation data'
extra:
  identifiers:
    - biotools:beat
    - doi:10.1038/nmeth.3252
  parent_recipe:
    name: bioconductor-beat
    path: recipes/bioconductor-beat
    version: 1.18.0

