package:
  name: python-libsbml
  version: "5.17.0"

source:
  url: https://files.pythonhosted.org/packages/bc/0f/c0769b20c90a6d431d3c78842a8670156bb2e08074662a070bfefbdc56b2/python-libsbml_5.12.0.tar.gz
  sha256: 550fc7c5e614629786aecadf80e898e318149cde00537842e96053820f5d2b3f
  patches:
    - fix_path.patch

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - libxml2
    - bzip2
    - libxml2
  run:
    - python
    - bzip2
    - libxml2

test:
  imports:
    - libsbml

about:
  home: http://sbml.org
  license: LGPL
  summary: 'LibSBML Python API. LibSBML is a library for reading, writing and manipulating the Systems Biology Markup Language (SBML).'
