package:
  name: multiphate 
  version: 0.5 

source:
  url: https://github.com/carolzhou/multiPhATEb/archive/a706cac23339588fe9fa4a34d607fcdcabccfe5a.tar.gz
  sha256: abebe1512485f6a2317d0108a18655b56745a692c6073ab6bb5d072e0ac6f501

build:
  number: 0
  noarch: python 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - tRNAscan-SE
    - emboss
    - biopython
    - blast
    - glimmer
    - prodigal

test:
  imports:
    - multiPhate.py

about:
  home: https://github.com/carolzhou/multiPhATEb.git
  license: BSD3
  license_file: BSD-3.pdf
  summary: 'De novo annotation of phage genome sequence.'
