{% set version = "1.2.1" %}
{% set name = "BEARscc" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: ab3b847752feb2898b3fa5651a69ca09a00a722969e872ba2317fa840e450e7e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: testthat, cowplot, knitr, rmarkdown, BiocStyle, NMF
requirements:
  host:
    - 'bioconductor-singlecellexperiment >=1.4.0,<1.5.0'
    - r-base
    - r-data.table
    - r-ggplot2
  run:
    - 'bioconductor-singlecellexperiment >=1.4.0,<1.5.0'
    - r-base
    - r-data.table
    - r-ggplot2
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'BEARscc is a noise estimation and injection tool that is designed to assess putative single-cell RNA-seq clusters in the context of experimental noise estimated by ERCC spike-in controls.'

