{% set version = "1.20.1" %}
{% set name = "CoverageView" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: a221cf60cfb9c7c8d7855a71ce0085bacc343eaf73d4ab3e9e8052b389a29498
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-genomicalignments >=1.18.0,<1.19.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.35.0'
    - 'bioconductor-iranges >=2.16.0,<2.17.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.35.0'
    - 'bioconductor-rtracklayer >=1.42.0,<1.43.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.21.0'
    - r-base
  run:
    - 'bioconductor-genomicalignments >=1.18.0,<1.19.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.35.0'
    - 'bioconductor-iranges >=2.16.0,<2.17.0'
    - 'bioconductor-rsamtools >=1.34.0,<1.35.0'
    - 'bioconductor-rtracklayer >=1.42.0,<1.43.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.21.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This package provides a framework for the visualization of genome coverage profiles. It can be used for ChIP-seq experiments, but it can be also used for genome-wide nucleosome positioning experiments or other experiment types where it is important to have a framework in order to inspect how the coverage distributed across the genome'

