{% set version = "1.10.2" %}
{% set name = "scran" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: ef585de49f2f799c5bb0747a0de502271d4e3efca94a176ab674e037328daf1e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: testthat, BiocStyle, knitr, beachmat, HDF5Array, irlba, org.Mm.eg.db, DESeq2, monocle, pracma, Biobase, aroma.light
# SystemRequirements: C++11
requirements:
  host:
    - 'bioconductor-beachmat >=1.4.0,<1.5.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.29.0'
    - 'bioconductor-biocneighbors >=1.0.0,<1.1.0'
    - 'bioconductor-biocparallel >=1.16.0,<1.17.0'
    - 'bioconductor-delayedarray >=0.8.0,<0.9.0'
    - 'bioconductor-delayedmatrixstats >=1.4.0,<1.5.0'
    - 'bioconductor-edger >=3.24.0,<3.25.0'
    - 'bioconductor-limma >=3.38.0,<3.39.0'
    - 'bioconductor-rhdf5lib >=1.4.0,<1.5.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.21.0'
    - 'bioconductor-scater >=1.10.0,<1.11.0'
    - 'bioconductor-singlecellexperiment >=1.4.0,<1.5.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.13.0'
    - r-base
    - r-dynamictreecut
    - r-igraph
    - r-matrix
    - 'r-rcpp >=0.12.14'
    - r-statmod
  run:
    - 'bioconductor-beachmat >=1.4.0,<1.5.0'
    - 'bioconductor-biocgenerics >=0.28.0,<0.29.0'
    - 'bioconductor-biocneighbors >=1.0.0,<1.1.0'
    - 'bioconductor-biocparallel >=1.16.0,<1.17.0'
    - 'bioconductor-delayedarray >=0.8.0,<0.9.0'
    - 'bioconductor-delayedmatrixstats >=1.4.0,<1.5.0'
    - 'bioconductor-edger >=3.24.0,<3.25.0'
    - 'bioconductor-limma >=3.38.0,<3.39.0'
    - 'bioconductor-rhdf5lib >=1.4.0,<1.5.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.21.0'
    - 'bioconductor-scater >=1.10.0,<1.11.0'
    - 'bioconductor-singlecellexperiment >=1.4.0,<1.5.0'
    - 'bioconductor-summarizedexperiment >=1.12.0,<1.13.0'
    - r-base
    - r-dynamictreecut
    - r-igraph
    - r-matrix
    - 'r-rcpp >=0.12.14'
    - r-statmod
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'Implements functions for low-level analyses of single-cell RNA-seq data. Methods are provided for normalization of cell-specific biases, assignment of cell cycle phase, detection of highly variable and significantly correlated genes, correction of batch effects, identification of marker genes, and other common tasks in single-cell analysis workflows.'
extra:
  identifiers:
    - biotools:scran
  parent_recipe:
    name: bioconductor-scran
    path: recipes/bioconductor-scran
    version: 1.8.4

