{% set name = "dxpy" %}
{% set version = "0.271.0" %}
{% set sha256 = "4dd142da0969f552f60ccb2506f8e4cef840a629e8052fbbedef8d1e2ff2e40a" %}

package:
  name: {{ name }}
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true # [not py27]
  entry_points:
    - dx = dxpy.scripts.dx:main
    - dx-app-wizard = dxpy.scripts.dx_app_wizard:main
    - dx-build-app = dxpy.scripts.dx_build_app:main
    - dx-build-applet = dxpy.scripts.dx_build_applet:main
    - dx-build-report-html = dxpy.scripts.dx_build_report_html:main
    - dx-genes-to-gff = dxpy.scripts.dx_genes_to_gff:main
    - dx-genes-to-gtf = dxpy.scripts.dx_genes_to_gtf:main
    - dx-mappings-to-fastq = dxpy.scripts.dx_mappings_to_fastq:main
    - dx-mappings-to-sam = dxpy.scripts.dx_mappings_to_sam:main
    - dx-reads-to-fastq = dxpy.scripts.dx_reads_to_fastq:main
    - dx-spans-to-bed = dxpy.scripts.dx_spans_to_bed:main
    - dx-variants-to-vcf = dxpy.scripts.dx_variants_to_vcf:main

requirements:
  host:
    - argcomplete >=1.9.4
    - beautifulsoup4 >=4.4.1
    - cryptography <=2.2.2
    - fusepy >=2.0.2
    - futures >=3.0.4
    - pip
    - psutil >=3.3.0
    - python
    - python-dateutil >=2.5
    - python-magic >=0.4.6
    - requests >=2.8.0
    - setuptools
    - websocket-client >=0.53.0
    - ws4py >=0.3.2
    - xattr >=0.6.4
  run:
    - argcomplete >=1.9.4
    - beautifulsoup4 >=4.4.1
    - cryptography <=2.2.2
    - fusepy >=2.0.2
    - futures >=3.0.4
    - psutil >=3.3.0
    - python
    - python-dateutil >=2.5
    - python-magic >=0.4.6
    - requests >=2.8.0
    - websocket-client >=0.53.0
    - ws4py >=0.3.2
    - xattr >=0.6.4

test:
  # Python imports
  imports:
    - dxpy
    - dxpy.bindings
    - dxpy.cli
    - dxpy.packages
    - dxpy.scripts
    - dxpy.templating
    - dxpy.utils
  commands:
    - dx --help
    - dx-app-wizard --help
    - dx-build-app --help
    - dx-build-applet --help
    - dx-build-report-html --help
    - dx-genes-to-gff --help
    - dx-genes-to-gtf --help
    - dx-mappings-to-fastq --help
    - dx-mappings-to-sam --help
    - dx-reads-to-fastq --help
    - dx-spans-to-bed --help
    - dx-variants-to-vcf --help
  requires:
    - mock ==2.0.0
    - coverage ==3.7.1
    - pexpect ==4.2
    - pyopenssl ==16.2.0
    - pytest ==3.5.1

about:
  home: https://github.com/dnanexus/dx-toolkit
  license: Apache-2.0
  license_family: Apache
  summary: DNAnexus Platform API bindings for Python
  doc_url: https://wiki.dnanexus.com/downloads#DNAnexus-Platform-SDK
  dev_url: https://github.com/dnanexus/dx-toolkit

extra:
  recipe-maintainers:
    - notestaff

