{% set version = "1.34.1" %}
{% set name = "flowTrans" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 8b41353b5fec0fd78a31a06341267f01968ce1a4e7c29bf6f691adff882f5b71
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-flowclust >=3.20.0,<3.21.0'
    - 'bioconductor-flowcore >=1.48.0,<1.49.0'
    - 'bioconductor-flowviz >=1.46.0,<1.47.0'
    - r-base
  run:
    - 'bioconductor-flowclust >=3.20.0,<3.21.0'
    - 'bioconductor-flowcore >=1.48.0,<1.49.0'
    - 'bioconductor-flowviz >=1.46.0,<1.47.0'
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Profile maximum likelihood estimation of parameters for flow cytometry data transformations.'

