{% set version="3.10.1" %}
package:
  name: rtg-tools
  version: {{ version }}

source:
  url: https://github.com/RealTimeGenomics/rtg-tools/releases/download/{{ version }}/rtg-tools-{{ version }}-nojre.zip
  sha256: 6f2f84b9d6fdedcf6e2d9d30358b37d74566f4336221dee06c94e8d609b907e6

build:
  number: 0
  noarch: generic

requirements:
  run:
    - openjdk

test:
  commands:
    - rtg vcfeval --help 2>&1 | grep "Usage"

about:
  home: https://github.com/RealTimeGenomics/rtg-tools
  license: BSD
  summary: RealTimeGenomics Tools -- Utilities for accurate VCF comparison and manipulation
